leftnav:
- identifier: 307a8cea-fae5-a506-a96f-65ac72b4610b
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 3c4e9a76-c767-69f7-c74a-794cc304c975
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: ebde0039-d561-423c-d400-9ee20f03662c
  name: Readings
  url: /pages/readings/
  weight: 30
- identifier: 4a1bc61d-149e-e4da-ab5f-f7bda7f8d1de
  name: Further Reading
  parent: ebde0039-d561-423c-d400-9ee20f03662c
  url: /pages/readings/further-reading
  weight: 40
- identifier: fab648cd-cd24-d2fb-58f6-6683017bdbd8
  name: Assignments
  url: /pages/assignments
  weight: 50
- identifier: 123d9850-bade-75e6-0d80-07dbec88681c
  name: Related Resources
  url: /pages/related-resources
  weight: 60
